# Generated by Django 2.0.6 on 2018-07-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='name',
        ),
    ]
