# Generated by Django 2.0.6 on 2018-07-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20180703_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exam_grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
